spring:
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    properties:
      schema.schema.registry.url: http://localhost:8081


### mongodb configuration ###
  data:
    mongodb:
      #uri: "mongodb://root:rootpassword@localhost:27017/order?authSource=admin"
      host: localhost
      port: 27017
      username: root
      password: rootpassword
      database: order
      authentication-database: admin






  #schema.registry.url: http://localhost:8081

application:
  topic:
    name: orders
