## spring related properties
spring:
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        specific.avro.reader: true
    properties:
      schema.registry.url: http://localhost:8081

### mongodb configuration ###
  data:
    mongodb:
      uri: "mongodb://root:rootpassword@localhost:27017/order?authSource=admin"

## application related properties
application:
  topic:
    producer:
     name: orders
    consumer:
      name: processed-orders

server:
  port: 8080

springdoc:
  api-docs:
    url: /v3/api-docs